-- AlterTable
ALTER TABLE "Plan" ADD COLUMN IF NOT EXISTS "planDescription" TEXT;
ALTER TABLE "Plan" ADD COLUMN IF NOT EXISTS "planCurrency" TEXT NOT NULL DEFAULT 'CLP';
ALTER TABLE "Plan" ADD COLUMN IF NOT EXISTS "planActive" BOOLEAN NOT NULL DEFAULT true;
